git config --global alias.s "status"
git config --global alias.d "diff"
git config --global alias.a "add"
git config --global alias.aa "add ."
git config --global alias.q "reset"
git config --global alias.dc "diff --cached"
git config --global alias.cim "commit --message"
git config --global alias.ciao "commit --amend --no-edit"
git config --global alias.co "checkout"
git config --global alias.coa "checkout ."
git config --global alias.cop "checkout --patch"
git config --global alias.l "log --numstat --graph --decorate"
git config --global alias.lp "log --patch --graph --decorate"
git config --global alias.qhp "reset HEAD^"
git config --global alias.ci "commit -v"
git config --global alias.cia "commit --amend -v"
git config --global alias.ap "add --patch"
git config --global alias.b "branch --sort=committerdate"
git config --global alias.bv "branch -v --sort=committerdate"
git config --global alias.bvv "branch -vv --sort=committerdate"
git config --global alias.cob "checkout -b"
git config --global alias.la "log --all --numstat --graph --decorate"
git config --global alias.m "merge"
git config --global alias.mo "merge --no-edit"
git config --global alias.lf "log --numstat --first-parent --graph --decorate"
git config --global alias.lfp "log --patch -m --first-parent --graph --decorate"
git config --global alias.bm "branch --sort=committerdate --merged"
git config --global alias.bn "branch --sort=committerdate --no-merged"
git config --global alias.ma "merge --abort"
git config --global alias.do "diff --ours"
git config --global alias.dt "diff --theirs"
git config --global alias.coo "checkout --ours"
git config --global alias.cot "checkout --theirs"
git config --global alias.conflicts "diff --name-only --diff-filter=U"
git config --global alias.cio "commit --no-edit"
git config --global alias.r "rebase"
git config --global alias.ri "rebase --interactive --autosquash"
git config --global alias.ra "rebase --abort"
git config --global alias.rc "rebase --continue"
git config --global alias.rs "rebase --skip"
git config --global alias.rp "rebase --preserve-merges"
git config --global alias.cif "!sh -c 'git commit --fixup=$1' -"
git config --global alias.dw "diff --word-diff"
git config --global alias.dcw "diff --cached --word-diff"
git config --global alias.f "fetch --prune"
git config --global alias.fa "fetch --all --prune"
git config --global alias.mf "merge --ff"
git config --global alias.ph "push"
git config --global alias.phf "push --force"
git config --global alias.pl "pull"
git config --global alias.plr "pull --rebase"
git config --global alias.rma "rebase master"
git config --global alias.rmi "rebase master --interactive --autosquash"
git config --global rerere.enabled "true"
git config --global merge.conflictstyle "diff3"
git config --global merge.ff "false"
git config --global pull.ff "only"
git config --global color.ui "auto"
git config --global color.branch "auto"
git config --global color.diff "auto"
git config --global color.interactive "auto"
git config --global color.status "auto"
